travis:
  secure:
    BINSTAR_TOKEN: w2YxrMGYPsYD0qwoZMQe+dSZNeb0KGNlJsgbkLnzS+KTW2dKCX3W2k0ushGYqBQ0RQabCAFoqleBFd5/6YqJ7CaKTXCtjYg3NVtTZxHwp68JjdmTyTrbniL+vVt1p3HoH8FrcXpJm5p32mV7WS5cfLtiNxYSPWUf7lumzvt8MwkmE40hyNengri9qQA8sj88BxXdI+NLhSo5s40fyNj4wFuhHG4tvpgjv76Bi3/P+KYyHKiUxZCn0aBFSASxaX+zDO4+KSEJMdZxVRI50AQbY1A9ybl9lX+K5Yc4o3sevd37pAd6CNpaqQE2pbDKb9/K3FGEpsWoK9FPuIjrfFkslJ6ufug9rUxZ4yV1wmLGRfDn3DXbp5XdZ+tGeRryjqxBL8/JHogFhtctsMBdxC8kph8qhzD0lY6MHigA0bB/u2pObo+hOohre6J/tckBWZ0zpXjeSDZkbl3Xh9obHbAWD6ADHN/RY7m3D+u2QlAwGb+jGqBMxwxriId+VX9oMHBr1sl/bb7EJBInfFUYl6jzPsvAxIqJ09f/uN/DhDaNLYdJdEWACq0ZIShFDSofqsepxKN/AXF/HSUuO8S15SDOX+42ULqwIZKWHVvJwDlNeNwEbR3MHDEUXy8GEniw6asLKrIpz95OPDqaMpNl10dtcpeupA34xMXO6yFfhJCu7go=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
