travis:
  secure:
    BINSTAR_TOKEN: wXfp4MZ5NJ0+mLpxQcxQrWgohDVxMjDNsDKvtaol5S19cUC+xIaFQIZgvWvahfk58I28XtEwFm5JKnQOYPPwPo4w9r/EEFetBTGahOTJkqlbK9ppKnZ2n+wHz6YruFqRszLSUHFifob4FScCg4u9TKzWuUvQr0MGPux7L/dMvTCjvum2KO2K6jhjD1PTy/Cnue8MO3r/jIOIxUlclGlVvm/nodtQn5r7CluyDDfeNfsTIezLeOK+N84YwhRP9oJEUfAuzc2LUruKpLSVm1bLb7LSufx6H+WPuYviQjvjlCX5XgJJh9wAycz/2KANhgR/tJAt63OJlE3IWZpLYNdL3rLMzqucgxBgZv2nf1YHcPhfGVa4yTLlRkJoub6L9EYtTI4r5b6Ph8JTipVaCoqkgnQe6eT2uvwuhkLPMk7qx/geNJYTR3xDjw8MFZ9AIqh45l7+545FEldKXM/vihTjfD/tdpcDY1ApMlgM1xbuIG5kuSw8V1Fx2zkFKIdJXFenfdpLnCy1TR0bUa4amMX/bavixY2xc8In2yVhXczk0Ltd+4kfK6tQJseO2k6+mRcG0bhjalyQp0NWyJH51iO0jkojALRQCaQrAPOxT/oF1X2T4jzDWy1pbe/Hz+XLCBd6aGghTuxTelDSz49ub1Gbn5SIj566iyAy5cNmFtNsapI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
